CivClassic/AnsibleSetup

templates/public/plugins/FactoryMod/config.yml.j2

Need to look re-look at enchantments since the ones that are erroring seem to be still correct based on https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html
Please put on CivTest and reply with any errors

First attempt at fiixing identifiers

---

templates/public/plugins/RandomSpawn/worlds.yml.j2

probably missing some of the newest cities but this is a good first set

RandomSpawn: add city spawnpoints

---

templates/public/plugins/RealisticBiomes/config.yml.j2

also fixed 30s dark oak tree grow time

biome fixes

---

templates/public/plugins/FactoryMod/config.yml.j2

-Added Uncarve pumpkin recipe to all cauldrons
-Kelp/Sea Pickles/Corals all added to bio lab
-Bells in Gold forge
-Blue ice at 1:8 ratio of packed ice in aesthetics factory
-Berry bush in bakery

1.14 recipes

---

templates/public/plugins/FactoryMod/config.yml.j2

Corrected the input and output of the `birch_to_sapling` recipe

Birch to Oak Sapling Recipe Fix

---

templates/public/plugins/RandomSpawn/worlds.yml.j2

Adds Westminster (Commonwealth) into the list of spawn locations.

Added Commmonwealth in RandomSpawn locations

---

templates/public/plugins/RealisticBiomes/config.yml.j2

still figuring out Dark Forest bugs, per this config they should be working, but they aren't as recorded by Oddish and found in-game by me. Going to look into RB code later to figure it out

more updates for crops/trees

---

templates/public/plugins/FactoryMod/config.yml.j2

The new dyes can be crafted using the old materials at a 1:1 ratio. 
Unlike the older ones, they can also be crafted with the new flowers, hence the PR.

Changed recipes to use the new white/brown/blue/black dyes

---

templates/public/plugins/SimpleAdminHacks/config.yml.j2

Intention is to help newfriends -- see conversation in #ask-an-admin-or-superfriend

Add minecart to starting inventory

---

templates/public/plugins/HiddenOre/config.yml.j2

HiddenOre vein reconfiguration

---

templates/public/plugins/Finale/config.yml.j2

As much fun as [this is](https://streamable.com/ux0vmr), let's fix that.

Fix fire invulnerability ticks

---

templates/public/plugins/FactoryMod/config.yml.j2

due to SAND/RED_SAND split smelt_glass no longer smelts red sand
adding new recipe so i can smelt my red sand

readd red sand smelting

---

templates/public/plugins/FactoryMod/config.yml.j2

Have not been needed since dirt factory was removed

Remove no longer used upgrade recipes

---

templates/public/plugins/FactoryMod/config.yml.j2

Scouter9001 grow mushrooms in bio lab

---

templates/public/plugins/SimpleAdminHacks/config.yml.j2

The correct mob name is Piglin, per https://github.com/CivClassic/SimpleAdminHacks/blob/master/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/basic/HumbugBatchOne.java#L90

Hoglin -> Piglin in config

---

templates/public/plugins/FactoryMod/config.yml.j2

Added Fox, Cat, Hoglin, Strider spawn eggs and fixed a few spawn egg formatting typos.

Add various spawn eggs

---

templates/public/plugins/RealisticBiomes/config.yml.j2

Only to be merged if https://github.com/CivClassic/RealisticBiomes/pull/27 is merged

Add Kelp to no bonemeal list

---

templates/public/plugins/FactoryMod/config.yml.j2

I refered to the recipe in two different ways. I swear I copied it from my test server, and I swear my test server worked perfectly.

Fix JSON Printing Plates

---

templates/public/plugins/FactoryMod/config.yml.j2

Adds some nice QOL recipes that give more lateral accessibility to get materials

Add a grinding mill factory

---

templates/public/plugins/ClearLag/config.yml.j2

Limits cod to only one school per chunk and will cull the rest

New ClearLagg 3.2.0 option for cod

---

templates/public/plugins/FactoryMod/config.yml.j2

I wanted to make it cool but it breaks factories so now it isn't cool but it does work.

Fix Lamp Black Dye not working in factory recipes

---

templates/public/plugins/SimpleAdminHacks/config.yml.j2

Reliant on https://github.com/CivClassic/SimpleAdminHacks/pull/55, https://github.com/CivClassic/SimpleAdminHacks/pull/54, https://github.com/CivClassic/SimpleAdminHacks/pull/52 being merged.

Add Diet's additions to the config

---

templates/public/plugins/RealisticBiomes/config.yml.j2

Removed duplicate "other" biome type from the biome list and changed crops that grew in the "other" biome to grow with the same rate in the "nether" and "end" biomes.

Removed "other" biomes

---

templates/public/plugins/JukeAlert/config.yml.j2

Should only be merged with https://github.com/CivClassic/JukeAlert/pull/45

Fix config for jatogglelever

---

templates/public/spigot.yml.j2

https://github.com/CivClassic/AnsibleSetup/issues/112

Increase timeout-time

---

templates/public/plugins/ClearLag/config.yml.j2

Buff witherskeles while nether biome doesn't spawn them

Buff witherskeles

---

templates/public/plugins/JukeAlert/config.yml.j2

Noteblocks: 1 month active / 1 month dormant
Jukes: 2 months active / 2 months dormant
Expecting discussion on this but probably should be finalised soon

Snitch cull time

---

tasks/deploy-server.yml
tasks/deploy-tuinity.yml
templates/public/tuinity.yml.j2
variables/all.yml

Would like to test from a clean slate but this did work on the test server

Hopefully add tuinity to ansible

---

templates/public/plugins/SimpleAdminHacks/config.yml.j2

Fix spacing

---

templates/public/plugins/SimpleAdminHacks/config.yml.j2

Adding new 1.16 blocks + brewing stands to chunk limits.
If you do not merge this I will make blast furnace land. This is not a threat, it is a promise.

Adding new 1.16 blocks + brewing stands to chunk limits.

---

templates/public/plugins/FactoryMod/config.yml.j2

added flint to repair and factory creation

Updated Grinding Mill Nerf (I understand github a bit better)

---

templates/public/plugins/FactoryMod/config.yml.j2

Reverts CivClassic/AnsibleSetup#210

Revert "Updated Grinding Mill Nerf (I understand github a bit better)"

---

templates/public/plugins/FactoryMod/config.yml.j2

Removed all the uncarve recipes for converting carved pumpkins into normal pumpkins.

Removing the uncarve recipes

---

templates/public/plugins/SimpleAdminHacks/config.yml.j2

Add in /fm message to dog facts

Add in /fm message to dog facts
