CivClassic/AnsibleSetup

templates/public/plugins/FactoryMod/config.yml.j2

Added:
-Recipes
-smelt smooth stone
-make smooth stone slab
Renamed/Corrected:
- Recipes that claimed they created `smooth_stone`, that actually created `stone` were retitled, and the involved "make" functions were corrected.
- Because `double_stone_slab:8` blocks no longer exist, and are now functionally the same thing as `smooth_stone`, the lore of `double block` was removed, and the output doubled, to give a equal number of smooth stone slabs as crafting by hand.
- Because `double_stone_slab:8` was essentially two smooth stone slabs, the corresponding recipe for `stone_slabs` would have just been a regular `stone` block, so the lore of `double block` was removed.
Balance:
- Gave a 1.25x multiplier for smooth stone when smelting. (64 in:80 out)
- Because the original slab recipe assumed …

Correction/additions to recipes for Smooth_Stone

---

templates/public/plugins/FactoryMod/config.yml.j2

Due to the change from damage values to independent blocks when defining block varients, the current state of the charcoal factory was limiting inputs to oak logs exclusively, rather than the expected behavior of using whatever log they were inputting to create charcoal.
I just made a new recipe for each log type to convert to charcoal. Unless there exists a way for factorymod to lump all logs together still, this is the best solution to the issue I could come up with.
An advantage of doing things this way though, is if people wanted to, you all could tweak individual log to charcoal values depending on say, how difficult it was to automate and/or chop down each type of tree. But that's by no means necessary.

Charcoal Factory Corrections

---

templates/public/plugins/FactoryMod/config.yml.j2

I just made a new recipe with the same ratios to allow oak to be converted to each type of sapling, to make the behavior consistent with what people experienced in 1.12.
If the change was intentional, feel free to let me know. But it seemed to just be another issue with block variants being converted from damage values to actual independent blocks.
If there is a way to get the same functionality we had in 1.12.2, where you could just put any sapling in, and it would auto convert it to oak, without having to select a specific recipe, that'd be ideal, but as far as I know, because there are no more damage value varients like there used to be, that isn't currently possible (Within the limits of my admittedly shallow understanding of factorymod)
Charcoal also likely has this same issue, …

New Recipes to Fix Sapling Conversions

---

templates/public/plugins/FactoryMod/config.yml.j2

- Removed line (6) `default_menu_factory: Dirt Factory`
- Converted all mentions of `dirt!` to `dirt` except for line (5948), which, as best as I can tell, has to do with fossils.
- Removed all lines made up entirely of `        name: Dirt!`
- Added a blank line at the end cause github was asking me to.
- Removed all recipes accessed via the `Dirt Factory`, including all recipes in the attached file.
[new 2.txt](https://github.com/CivClassic/AnsibleSetup/files/4578605/new.2.txt)

Removing Dirt!

---

templates/public/plugins/SimpleAdminHacks/config.yml.j2

- Added an `OAK_BOAT` to the a new player's spawn inventory
- Gave `OAK_BOAT` unique lore to match the the other spawn items
- Corrected `BED` to `WHITE_BED` to be consistent with 1.14's item naming, as and I chose white specifically to allow new players to dye their beds to whatever color they'd like.
- Confirmed that `COOKIE` is the correct item type.

Spawn Item Changes

---

templates/public/plugins/RealisticBiomes/config.yml.j2

Also: refactored & changed some of the biome config so it becomes more consistent with the old one
Currently only the six base vanilla trees are working, RealisticBiomes apparently only parses Materials in the config right now and not TreeTypes like it used to, so stuff like giant 2x2 spruce trees are known to not be working. (This also goes for Animal breeding as well, but that's not as important)

Added tree/crop inheritance from old config

---

templates/public/plugins/FactoryMod/config.yml.j2

This adds a recipe to cook 32 cactus into 48 green dye using a Grill.
The conversion rate is the same as other grill recipes. It's mostly a QoL over using tons of furnace to get a bunch of green dye.
The grill was chosen because it makes more sense to use a damn grill over the same thing that you'd use for smelting sand into glass.

Added recipe for cooking cactus into green dye in Grill

---

templates/public/plugins/FactoryMod/config.yml.j2

This adds a recipe in the Grill to cook kelp into dried kelp.
The conversion rate is the same as other grill recipes. The grill was chosen over other factories because dried kelp is edible and because from a realistic perspective, a stone smelter would be overkill for drying up algae.

Added recipe for cooking kelp into dried kelp

---

templates/public/plugins/Orebfuscator/config.yml.j2

The overall changes will just show all green. Look at the individual commits to see what's happening.
I've added back the missing entries from the [old config](https://github.com/CivClassic/Configs/blob/master/Orebfuscator4/config.yml#L57-L59), as well as added the new blocks from 1.13 and 1.14. I've left out the blocks that are exclusively villager task based (such as Smithing Tables) and blocks that have aesthetic purposes (like Campfires and Lecterns). Other blocks that are disabled in Civclassic (like Scaffolding and Grindstones) have been left out.
Some of the changes to `RandomBlocks` and `ObfuscateBlocks` are just re-organisation to put the ores together and such so it's more readable for future contributors. I've removed ore completely as the.. confetti blocks.. for a lack of a …

Orebfuscator update

---

templates/public/plugins/FactoryMod/config.yml.j2

Made in response to https://github.com/CivClassic/AnsibleSetup/issues/29 
Unsure whether fossil 'chance' values need to be specific so I've replaced the bucket output

Replace crack_fossil bucket output with heart of the sea

---

templates/public/plugins/SimpleAdminHacks/config.yml.j2

- Currently CivClassic seems to have nothing enforcing block limits (eg. try placing 64 dropper's in a single chunk). 
- Remove SLIME_BLOCK as SAH only limits tile entities.

Enable block limits

---

templates/public/plugins/HiddenOre/config.yml.j2

Halve coal/iron cluster size. Gold, Lapis more common but smaller clusters. Redstone more common same size cluster. Fossils slightly more common.

Balance ore chances

---

templates/public/plugins/FactoryMod/config.yml.j2

As the title suggests, this adds several recipes for new 1.16 blocks.
It also changes the Lapis Lazuli requirement for Blue Coral to Blue Dye so that it can be produced from blue flowers.
Here's the propositions for 1.16 nether blocks. These can be produced in the aesthetic factory.
- 32 dirt + 32 soul sand => 64 soul soil
- 32 cobble + 32 netherrack => 64 blackstone. 
Blackstone is the nether equivalent of cobblestone. Obtaining by mixing netherrack and cobblestone seems natural.
- 64 netherrack + 4 blue ice + 4 soul soil => 96 basalt
This one might seems weirder and more controversial than the rest. That's because basalt can be obtained with a [generator](https://minecraft.gamepedia.com/Basalt#Post-generation) using lava, soul soil and blue ice.
Contrary to the generator, this recipe …

Added several 1.16 recipes

---

templates/public/plugins/Orebfuscator/config.yml.j2

See #68 
- Removed tnt and air pockets
- Added barrels to the list of obfuscable blocks
Note: Unlike #62 , Orebfuscator5 loads the config from `Orebfsuscator/` and not `Orebfuscator5/`.

Updated Orebfuscator config

---

templates/public/plugins/CivChat2/config.yml.j2

this makes triangulation (using local chat colors) less effective

gray local chat for 800m+ distance (outer 200m ring)

---

templates/public/plugins/HiddenOre/config.yml.j2

Not sure but maybe the yml syntax was wrong (compared to stone varieties list which work)

Fix quartz spawning?

---

templates/public/plugins/FactoryMod/config.yml.j2

You can get bee eggs from fossils, but as there are no bee nests spawned in the world it is impossible to get honeycomb to make bee hives. This would use phantom membranes to bypass that and make beehives to then farm bees to produce honey.

Add beehive recipe

---

templates/public/plugins/FactoryMod/config.yml.j2

Brick blocks are easier to create via the basic smelter and would be more appropiate than individual bricks, which have to be smelted in a furnace manually.

Make Bakeries require brick blocks.

---

templates/public/plugins/FactoryMod/config.yml.j2

This is a proposition for:
2 ghast tears + 64 obsidian => 64 crying obsidian
Crying obsidian has the same hardness as regular obsidian. The main difference is that it emits light (10).
I think the 2 ghast tears justify this small improvement, while also giving more use to the tears. 
EDIT: It is worth noting that crying obsidian can be used to make respawn anchors. They don't work in the overworld/end and their explosions are [disabled by default](https://github.com/CivClassic/SimpleAdminHacks/pull/23).

Added recipe for crying obsidian

---

templates/public/plugins/FactoryMod/config.yml.j2

By making a book filled with JSON Raw Text and the running the recipe, it'll take the raw text, sanitize it, and then output a printing plate that can be used as normal to print very fancy books.
To have multiple pages, you simply insert the string `<<PAGE>>` to split off a new page.
(text copied from https://github.com/CivClassic/FactoryMod/pull/39 for future reference)

Add JSON Printing Plate recipe

---

templates/public/plugins/Orebfuscator/config.yml.j2

removed orbfuscation sections for nether and end - not present/enabled in old config
enabled fastgaze and set proximity distance to 8
readded jukes noteblocks and sponges to proximity, also added bone blocks
proximity uses block below by default, this seems desirable so the end and overworld can share a config
added air to orebfuscation

cleaned up and adjusted in line with old config

---

templates/public/plugins/ExilePearl/config.yml.j2

To satisfy https://github.com/CivClassic/ExilePearl/issues/58 , I think it would make more sense to leverage the wealth of knowledge available on the CivWiki rather than adding more cumbersome in-game guides

Add website to visit for pearled info

---

templates/public/plugins/FactoryMod/config.yml.j2

leaves now drop sticks which are not consumed in any great quantities unlike logs+leaves, meaning tree farming now produces many relatively useless sticks as a byproduct
allowing sticks -> chests effectively provides a minor buff to tree farm wood output
this recipe is 1:1 with crafting chests from planks which could be changed if necessary

add sticks -> chest carpentry recipe

---

templates/public/plugins/FactoryMod/config.yml.j2

In the Charcoal Factory, you can now make 64 black dye using 64 charcoal. 
In my opinion, black dye is too hard to obtain for building, even when mobs are enabled. Right now with basically no squids spawning there is no way to obtain black dye in bulk. 
This recipe alleviates some of the pressure by adding a way to get black dye using charcoal. However it is also somewhat balanced in the fact that ink sacs are still needed for making books, thus giving them a use that this recipe does not replace.
Reminder: In 1.13+ versions ink sacs and black dye are two seperate items. You can craft ink sacs into black dye, but not the other way around. The printing press takes specifically ink sacs.

Add a lamp black dye recipe made from charcoal

---

templates/public/paper.yml.j2

Rate was set to 300 ticks which despawns dropped cobblestone after 15 seconds. Removing cobblestone from the config should make it despawn normally

Prevent cobblestone from quickly despawning

---

templates/public/plugins/FactoryMod/config.yml.j2

Two banner patterns are impossible to obtain on classics, the globe pattern that requires trading with a villager and the piglin pattern that can only be found while looting [Bastion Remnants](https://minecraft.gamepedia.com/Bastion_Remnant). This adds recipes to craft them in the Printing Press.

Add impossible banner pattern recipes

---

templates/public/plugins/RealisticBiomes/config.yml.j2

> Similar to grass blocks, the player can apply bone meal to nylium. This nylium, along with nearby nylium, generate vegetation that occurs in their native biome (crimson nylium generates mostly crimson forest vegetation and warped nylium generates mostly warped forest vegetation).
Is there a reason this should be disabled? Currently crimson/warped roots and nether sprouts are unobtainable

Allow bonemealing nylium

---

templates/public/plugins/ClearLag/config.yml.j2

currently slimes rarely spawn, and will immediately despawn if they've been alive longer than 1200 seconds i believe? which is pretty atrocious when attempting to farm them whatsoever.

Buff slimes

---

templates/public/plugins/FactoryMod/config.yml.j2

Remove black dye recipe, it was added because squids were not spawning, and the recipes addition nerfed a niche market. squids are now plentiful.

black dye removal

---

templates/public/plugins/FactoryMod/config.yml.j2

Since Wing's [commit](https://github.com/CivClassic/AnsibleSetup/commit/bd24ac3dd988dc07db1dcb5778dd712496d2c64c) that makes uncarving pumpkins 64x cheaper, this compacted variant should be removed. This recipe is singularly irregular, it's the only non-XP related recipe that processes compacted items, which fundamentally undermines the balancing of compaction; that XP recipes require compacted items because you simply cannot store that many items in a double chest, it's a necessity.. but uncarving pumpkins?

Remove Uncarve [Compacted] Pumpkins

---

templates/public/plugins/FactoryMod/config.yml.j2

You can prepay the materials for a compactor repair to make a compact repair kit. You then can use a compact repair kit to repair a compactor.
This resolves a common complaint about compactors that it is annoying to constantly repair them.

Add compact repair kits

---

templates/public/plugins/SimpleAdminHacks/config.yml.j2

Adding the piston changes made it so pistons could no longer move observers, totally breaking flying machines and destroying redstone applications.

Rollback piston changes, it didn't work

---

templates/public/plugins/FactoryMod/config.yml.j2

Concrete powder now takes 64 stone, 1 egg, and 4 dye, bringing it into the scale of materials used by recipes in the aesthetic factory.
There are now harden concrete recipes that convert concrete powder into concrete using 1 water bucket (refunding the bucket)
These changes are untested. I was about to go to sleep, but I did this instead. Errors are expected.

Concrete Factory Rebalance

---

templates/public/plugins/Orebfuscator/config.yml.j2

Mesa cliffs aren't getting obfuscated as they aren't made of stone like normal terrain

Obfuscate Terracotta to protect Mesa Biomes

---

templates/public/plugins/CraftEnhance/recipes.yml.j2

The proper identifier is "EMERALD_1" denoting the material and the amount. You can see it's usage in recipe19, and the identifier definition [here](https://github.com/CivClassic/AnsibleSetup/blob/4b2ce8d02c7e5da9e8fee6d73269cd772b4c8b92/templates/public/plugins/CraftEnhance/items.yml.j2#L143-L146)

Fix "EMERALD" item identifier
